/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 16:31:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class choice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Accounts - Online Transport System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Acoount.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    /* Reset and base styles */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    min-height: 100vh; \r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background-color: #439bc4; \r\n");
      out.write("    background-image: url('https://us.123rf.com/450wm/colorfuelstudio/colorfuelstudio2001/colorfuelstudio200100259/138510894-school-cute-activity-teacher-teach-vector-illustration.jpg?ver=6'); /* Replace with your image path */\r\n");
      out.write("    background-size: cover; \r\n");
      out.write("    background-repeat: no-repeat; \r\n");
      out.write("    background-position: center; \r\n");
      out.write("    color: #333;\r\n");
      out.write("    line-height: 1.0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation */\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #004d99;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    max-width: 1200px; \r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".system-name {\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 40px; \r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a {\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a:hover {\r\n");
      out.write("    color: #ffcc00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a.active {\r\n");
      out.write("    font-weight: bold; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Buttons */\r\n");
      out.write(".btn-primary {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Section Styling */\r\n");
      out.write(".auth-container {\r\n");
      out.write("    max-width: 500px; \r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    padding: 50px; \r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container h2 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #004d99;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container form div {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    appearance: none; \r\n");
      out.write("    -webkit-appearance: none; \r\n");
      out.write("    -moz-appearance: none; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container select:focus {\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-color: #007bff; \r\n");
      out.write("    box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container p {\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container p a {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Accounts Section */\r\n");
      out.write(".accounts-section {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    min-height: calc(100vh - 100px); \r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accounts-section h2 {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #004d99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".accounts-section p {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profiles Section Styling */\r\n");
      out.write(".services-section {\r\n");
      out.write("    padding: 60px 0;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".services-section h1 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 2.5rem;\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    margin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".service-card {\r\n");
      out.write("    background: white;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".service-card h2 {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".service-card p {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".learn-more-btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: background 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".learn-more-btn:hover {\r\n");
      out.write("    background: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".learn-more-btn i {\r\n");
      out.write("    margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider {\r\n");
      out.write("    border: 1px dashed #ddd;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profiles Wrapper */\r\n");
      out.write(".profiles-wrapper {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: flex-start; \r\n");
      out.write("    gap: 20px; \r\n");
      out.write("    max-width: 1200px; \r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("    padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card {\r\n");
      out.write("    flex: 1; \r\n");
      out.write("    max-width: 48%; \r\n");
      out.write("    background-color: white;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card h2 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card p {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card a.learn-more-btn {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: background 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card a.learn-more-btn:hover {\r\n");
      out.write("    background: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-card img.profile-image {\r\n");
      out.write("    width: 100%; \r\n");
      out.write("    max-width: 150px; \r\n");
      out.write("    height: auto; \r\n");
      out.write("    margin-bottom: 15px; \r\n");
      out.write("    border-radius: 50%; \r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Footer */\r\n");
      out.write("footer {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background-color: #004d99;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 15px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media a img {\r\n");
      out.write("    width: 24px; \r\n");
      out.write("    height: 24px; \r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media a img:hover {\r\n");
      out.write("    transform: scale(1.2); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        margin: 10px auto;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body style=\"background-color: #f0f8ff; background-image: url('https://w7.pngwing.com/pngs/929/974/png-transparent-blue-stripe-screenshot-blue-sky-daytime-sky-blue-background-blue-angle-other-thumbnail.png'); background-size: cover; background-repeat: no-repeat; background-position: center;\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("          <img src=\"https://marketplace.canva.com/EAF5lVrtgYg/1/0/1600w/canva-blue-and-orange-logistics-logo-rOf-eNSosdE.jpg\" alt=\"System Logo\" class=\"logo\" />\r\n");
      out.write("          <span class=\"system-name\">GoFleet</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("          <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"Ridebooking.jsp\">Book a Ride</a></li>\r\n");
      out.write("          <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"addComplaint.jsp\">Complain Us</a></li>\r\n");
      out.write("          <li><a href=\"choice.jsp\" class=\"active\">Accounts</a></li> \r\n");
      out.write("          <li><a href=\"DataForm.jsp\">Driver</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"accounts-section\">\r\n");
      out.write("      <h2>Account Management</h2>\r\n");
      out.write("      <p><b> your transport account or create a new one below.</b></p>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"profiles-wrapper\">\r\n");
      out.write("        <!-- Login Section -->\r\n");
      out.write("        <div class=\"profile-card\">\r\n");
      out.write("          <h2><i class=\"fas fa-user\"></i> Login</h2>\r\n");
      out.write("          <img src=\"https://img.freepik.com/premium-vector/secure-login-form-page-with-password-computer-padlock-3d-vector-icon-cartoon-minimal-style_365941-1119.jpg?semt=ais_hybrid&w=740\" alt=\"Login\" class=\"profile-image\" />\r\n");
      out.write("          <p>Log in to manage your account, view your ride history, and update your payment methods. Stay connected with your travel needs.</p>\r\n");
      out.write("          <a href=\"login.jsp\" class=\"learn-more-btn\">Learn More <i class=\"fas fa-arrow-right\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sign Up Section -->\r\n");
      out.write("        <div class=\"profile-card\">\r\n");
      out.write("          <h2><i class=\"fas fa-id-card-alt\"></i> Sign Up</h2>\r\n");
      out.write("          <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaQQe0GgVxKpCBL_qgoKiqLHpUZUszBlzks_a3392F0wbCTXGnbCu69ASRZRUlaDLZFbM&usqp=CAU\" alt=\"Sign Up\" class=\"profile-image\" />\r\n");
      out.write("          <p>Create a new account to join our platform. Whether you're a passenger or a driver, enjoy seamless access to our services.</p>\r\n");
      out.write("          <a href=\"sign_up.jsp\" class=\"learn-more-btn\">Learn More <i class=\"fas fa-arrow-right\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      <p>&copy; 2025 Online Transport System. All Rights Reserved.</p>\r\n");
      out.write("      <div class=\"social-media\">\r\n");
      out.write("        <a href=\"https://facebook.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://logowik.com/content/uploads/images/t_672_fb_icon.jpg\" alt=\"Facebook\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://twitter.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/124/124021.png\" alt=\"Twitter\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://instagram.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://e7.pngegg.com/pngimages/722/1011/png-clipart-logo-icon-instagram-logo-instagram-logo-purple-violet-thumbnail.png\" alt=\"Instagram\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"api.js\"></script>\r\n");
      out.write("    <script src=\"auth.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      if (document.readyState === \"loading\") {\r\n");
      out.write("        document.addEventListener(\"DOMContentLoaded\", updateNavigation);\r\n");
      out.write("      } else {\r\n");
      out.write("        updateNavigation();\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
