/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 16:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Contact Us</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"transport-styles.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    /* Reset and base styles */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: \"Segoe UI\", Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    min-height: 100vh; \r\n");
      out.write("    margin: 0;\r\n");
      out.write("    background-color: #439bc4; \r\n");
      out.write("    background-image: url('https://png.pngtree.com/thumb_back/fh260/background/20240630/pngtree-sitting-on-bus-public-transport-details-blue-passenger-seat-image_15830791.jpg'); /* Optional: Add a background image */\r\n");
      out.write("    background-size: cover; \r\n");
      out.write("    background-repeat: no-repeat; \r\n");
      out.write("    background-position: center; \r\n");
      out.write("    color: #333;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation */\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #004d99;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    max-width: 1200px; \r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".system-name {\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 40px; \r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a {\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a:hover {\r\n");
      out.write("    color: #ffcc00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a.active {\r\n");
      out.write("    font-weight: bold; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Buttons */\r\n");
      out.write(".btn-primary {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Section Styling */\r\n");
      out.write(".auth-container {\r\n");
      out.write("    max-width: 500px; \r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    padding: 50px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container h2 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #004d99;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container form div {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    appearance: none; \r\n");
      out.write("    -webkit-appearance: none; \r\n");
      out.write("    -moz-appearance: none; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container select:focus {\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-color: #007bff; \r\n");
      out.write("    box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container p {\r\n");
      out.write("    margin-top: 15px;\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".auth-container p a {\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Footer */\r\n");
      out.write("footer {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background-color: #004d99;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media a img {\r\n");
      out.write("    width: 24px; \r\n");
      out.write("    height: 24px; \r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media a img:hover {\r\n");
      out.write("    transform: scale(1.2); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* About Section */\r\n");
      out.write(".about-content {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center; \r\n");
      out.write("    gap: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about-content img {\r\n");
      out.write("    max-width: 50%; \r\n");
      out.write("    border-radius: 10px; \r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about-content p {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    font-size: 1.4rem;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    justify-content:rightS; \r\n");
      out.write("    align-items: right; \r\n");
      out.write("    min-height: calc(100vh - 100px); \r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".about h2 {\r\n");
      out.write("    font-size: 2.5rem;\r\n");
      out.write("    color: #004d99;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Contact Section */\r\n");
      out.write(".contact-wrapper {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center; \r\n");
      out.write("    align-items: center; \r\n");
      out.write("    min-height: calc(100vh - 100px); \r\n");
      out.write("    padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact {\r\n");
      out.write("    max-width: 500px; \r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 20px; \r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 30px; \r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); \r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact h2 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: #004d99;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact form div {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact input,\r\n");
      out.write(".contact textarea {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact textarea {\r\n");
      out.write("    resize: none; \r\n");
      out.write("    height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Mission Box */\r\n");
      out.write(".mission-box {\r\n");
      out.write("    background-color: #f0f8ff; \r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border-radius: 10px; \r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); \r\n");
      out.write("    color: #004d99; \r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mission-box h2 {\r\n");
      out.write("    color: #6f30a3; \r\n");
      out.write("    font-size: 1.5rem;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mission-box p {\r\n");
      out.write("    color: #333; \r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    line-height: 1.1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        margin: 10px auto;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body style=\"background-color: #f0f8ff; background-image: url('https://img.freepik.com/premium-photo/website-internet-contact-us-page-concept-with-phone-chat-email-icons-symbol-telephone-mail-mobile-phone-website-page-contact-us-wide-web-banner-copy-space-blue-background_256259-2446.jpg'); background-size: 100%; background-repeat: no-repeat; background-position: right;\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("          <img src=\"https://marketplace.canva.com/EAF5lVrtgYg/1/0/1600w/canva-blue-and-orange-logistics-logo-rOf-eNSosdE.jpg\" alt=\"System Logo\" class=\"logo\" />\r\n");
      out.write("          <span class=\"system-name\">GoFleet</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("          <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("          <li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"Ridebooking.jsp\">Book a Ride</a></li>\r\n");
      out.write("          <li><a href=\"contact.jsp\" class=\"active\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"addComplaint.jsp\">Complain Us</a></li>\r\n");
      out.write("          <li><a href=\"choice.jsp\">Accounts</a></li>\r\n");
      out.write("          <li><a href=\"DataForm.jsp\">Driver</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"contact-wrapper\">\r\n");
      out.write("      <div class=\"contact\">\r\n");
      out.write("        <h2>Contact Us</h2>\r\n");
      out.write("        <form>\r\n");
      out.write("          <div>\r\n");
      out.write("            <label for=\"name\">Name:</label>\r\n");
      out.write("            <input type=\"text\" id=\"name\" name=\"name\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <label for=\"email\">Email:</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <label for=\"Contact Number\">Contact Number:</label>\r\n");
      out.write("            <input type=\"tel\" id=\"Contact Number\" name=\"Contact Number\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div>\r\n");
      out.write("            <label for=\"message\">Message:</label>\r\n");
      out.write("            <textarea id=\"message\" name=\"message\" required></textarea>\r\n");
      out.write("          </div>\r\n");
      out.write("          <button type=\"submit\" class=\"btn-primary\">Submit</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      <p>&copy; 2025 Online Transport System. All Rights Reserved.</p>\r\n");
      out.write("      <div class=\"social-media\">\r\n");
      out.write("        <a href=\"https://facebook.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://logowik.com/content/uploads/images/t_672_fb_icon.jpg\" alt=\"Facebook\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://twitter.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://cdn-icons-png.flaticon.com/512/124/124021.png\" alt=\"Twitter\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://instagram.com\" target=\"_blank\">\r\n");
      out.write("          <img src=\"https://e7.pngegg.com/pngimages/722/1011/png-clipart-logo-icon-instagram-logo-instagram-logo-purple-violet-thumbnail.png\" alt=\"Instagram\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
