/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 16:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Online Transport System - Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * { box-sizing: border-box; }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            background: url('images/pngtree-sitting-on-bus-public-transport-details-blue-passenger-seat-image_15830791.jpg') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* HEADER */\r\n");
      out.write("        /* Navigation */\r\n");
      out.write("header {\r\n");
      out.write("    background-color: #004d99;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 15px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("    max-width: 1200px; \r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo-container {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".system-name {\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 40px; \r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a {\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a:hover {\r\n");
      out.write("    color: #ffcc00;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links li a.active {\r\n");
      out.write("    font-weight: bold; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Buttons */\r\n");
      out.write(".btn-primary {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("        /* HERO */\r\n");
      out.write("        .hero {\r\n");
      out.write("            background: linear-gradient(135deg, #2980b9, #3498db);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 60px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .hero h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 3em;\r\n");
      out.write("        }\r\n");
      out.write("        .hero p {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* CONTENT CARDS */\r\n");
      out.write("        .content {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            background-color: #F0F5FF;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0,0,0,0.1);\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("        }\r\n");
      out.write("        .card i {\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            color: #2980b9;\r\n");
      out.write("        }\r\n");
      out.write("        .card h3 {\r\n");
      out.write("            margin: 15px 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .card p {\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* FOOTER */\r\n");
      out.write("        footer {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: #004d99;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        footer p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .social-media {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .social-media a img {\r\n");
      out.write("            width: 24px;\r\n");
      out.write("            height: 24px;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .social-media a img:hover {\r\n");
      out.write("            transform: scale(1.2);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("            <img src=\"https://marketplace.canva.com/EAF5lVrtgYg/1/0/1600w/canva-blue-and-orange-logistics-logo-rOf-eNSosdE.jpg\" alt=\"System Logo\" class=\"logo\" />\r\n");
      out.write("            <span class=\"system-name\">GoFleet</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("            <li><a href=\"home.jsp\" class=\"active\">Home</a></li>\r\n");
      out.write("            <li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"Ridebooking.jsp\">Book a Ride</a></li>\r\n");
      out.write("            <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("            <li><a href=\"addComplaint.jsp\">Complain Us</a></li>\r\n");
      out.write("            <li><a href=\"choice.jsp\" class=\"active\">Accounts</a></li>\r\n");
      out.write("             <li><a href=\"DataForm.jsp\">Driver</a></li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hero\">\r\n");
      out.write("    <h1>Fast. Reliable. Safe.</h1>\r\n");
      out.write("    <p>Your one-stop platform for booking transport across the country</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <i class=\"fas fa-route\"></i>\r\n");
      out.write("        <h3>Check Routes</h3>\r\n");
      out.write("        <p>View all available transport routes and timings.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <i class=\"fas fa-ticket-alt\"></i>\r\n");
      out.write("        <h3>Book Tickets</h3>\r\n");
      out.write("        <p>Book tickets with just a few clicks, anytime, anywhere.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <i class=\"fas fa-user\"></i>\r\n");
      out.write("        <h3>User Account</h3>\r\n");
      out.write("        <p>Login or register to manage your bookings.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <p>&copy; 2025 Online Transport System. All Rights Reserved.</p>\r\n");
      out.write("    <div class=\"social-media\">\r\n");
      out.write("        <a href=\"https://facebook.com\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://logowik.com/content/uploads/images/t_672_fb_icon.jpg\" alt=\"Facebook\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://twitter.com\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://cdn-icons-png.flaticon.com/512/124/124021.png\" alt=\"Twitter\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://instagram.com\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://e7.pngegg.com/pngimages/722/1011/png-clipart-logo-icon-instagram-logo-instagram-logo-purple-violet-thumbnail.png\" alt=\"Instagram\" />\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
